### ISSUE TITLE
IE-10 error due to class properties transformation - add babel plugin es2015

### ISSUE THREAD

**Issue by rajeshps** [saidmoya12/tcomb-form-injector#2]
Hi,
Thanks for the wonderful addon to tcomb.
Out of the box works in Chrome and FF (when installed via npm), however fails in IE-10 with error 
`SCRIPT5007: Unable to get property 'hasError' of undefined or null reference: in Injector.js:148`
By installing this plugin and adding an entry to .babelrc file resolved the issue.

`babel-plugin-transform-es2015-classes`

```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": [
      "transform-class-properties",
       ["transform-es2015-classes", {
          "loose": true
        }]
  ]
}
```

Could you please add these and publish/release the latest to NPM as well?
I can do a PR if that helps, please let me know.

Thanks,
Rajesh

**Comment by saidmoya12** [comment]
Ready for version 3.0!! Checked on IE10

Please upgrade it!
