### ISSUE TITLE
Injected components lose focus on input (onChange) - fix is not to update props.key on re-render

### ISSUE THREAD

**Issue by rajeshps** [saidmoya12/tcomb-form-injector#3]
Injected components lose focus on input (onChange) due to unique key of element each time it renders.

Fix: Use any unique but consistent key rather than random number.

Change this line in `getInjectedElement()` function of Injector.js 
`props.key = Math.floor((Math.random() * 100) + 1);`
to
`props.key = this.props.key ? this.props.key : this.props.name;` (assuming name of component would always be unique)

Thanks!

**Comment by saidmoya12** [comment]
This is implemented now on version 3.0 please upgrade it!
